export const page = {
  transitionalplanning: "Transition Planning",
  employment: "Employment",
  career: "Career",
  jobpostings: "Job Postings",
  vocationaltraining: "Vocational Training",
  education: "Education",
  college: "College",
  transitionalprograms: "Transition Programs",
  independentliving: "Independent Living",
  livingathome: "Living At Home",
  assistedliving: "Assisted Living",
  grouphomes: "Group Homes",
  residentialprograms: "Residential Programs",
  dayprograms: "Day Programs",
  knowyourrights: "Know Your Rights",
  funding: "Funding",
  legalrights: "Legal Rights",
  getonthelist: "Get On The List",
  all: "All"
};
