export const info = {
  ageRange: ["< 9", "10-14", "15-19", "20-24", "> 25"],
  stateNames: [
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Federated States of Micronesia",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Marshall Islands",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Northern Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Palau",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virgin Island",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  process: [
    "I haven’t started planning my transition",
    "I have started transition planning through personal searches",
    "My school has helped me start transition planning",
    "I am far along in the planning process",
    "I have a concrete transition plan",
  ],
  disabilityCategories: [
    "Autism",
    "Blindness",
    "Deafness",
    "Emotional Disturbance",
    "Hearing Impairment",
    "Intellectual Disability",
    "Multiple Disabilities",
    "Orthopedic Impairment",
    "Other Health Impaired",
    "Specific Learning Disability",
    "Speech or Language Impairment",
    "Traumatic Brain Injury",
    "Visual Impairment",
  ],
  funds: ["in need of funds", "not in need of funds"],
  education: [
    "Attend a trade or vocational college",
    "Attend a junior or community college",
    "Attend a four year college/ university",
    "Not planning on acquiring postsecondary education",
    "Not sure/ undecided",
  ],
  employment: [
    "Attend vocational training program",
    "Find an internship or apprenticeship in a trade",
    "Find employment in an entry-level job",
    "Not looking for competitive employment",
    "Not sure/  undecided",
  ],
  independentLiving: [
    "Live in a public group home",
    "Continue living at home with family",
    "Live in a private group home or start a group home",
    "Assisted living",
    "Community housing",
    "Permanent residential program",
    "Unsure/ undecided",
  ],
};
